name: Deploy DEV

on:
  push:
    branches:
      - dev_brach_env2

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to DEV VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            echo "✅ Connecté au VPS"

            cd ${{ secrets.VPS_PATH_DEV }}
            echo "📂 Dossier DEV: $(pwd)"

            echo "---- GIT UPDATE ----"
            git fetch origin
            git checkout dev_brach_env2
            git reset --hard origin/dev_brach_env2
            git clean -fd

            echo "---- VERIFY COMMIT ----"
            git rev-parse HEAD

            echo "---- DOCKER CLEAN ----"
            docker-compose down --volumes --remove-orphans

            echo "---- DOCKER BUILD ----"
            docker-compose build --build-arg CACHE_BUST=$(git rev-parse HEAD)

            echo "---- DOCKER RUN ----"
            docker-compose up -d --force-recreate

            echo "---- DOCKER STATUS ----"
            docker ps -a

            echo "✅ Déploiement terminé"
