script: |
  echo "✅ Connecté au VPS"

  cd ${{ secrets.VPS_PATH_DEV }}
  echo "📂 Dossier DEV: $(pwd)"

  echo "---- GIT UPDATE ----"

  git checkout dev_brach_env2 || git checkout -b dev_brach_env2
  git pull origin dev_brach_env2

  echo "📦 Code à jour avec git pull"

  echo "---- BUILD CLIENT ----"
  cd client
  npm install
  npm run build
  cd ..

  echo "---- BUILD SERVER ----"
  cd server
  npm install
  npm run build
  cd ..

  echo "---- DOCKER CLEAN ----"

  docker-compose down --remove-orphans
  docker system prune -af
  docker volume prune -f

  echo "---- DOCKER BUILD ----"

  docker-compose build --no-cache
  docker-compose up -d

  docker ps -a

  echo "✅ Déploiement terminé"
